export enum AccountStatus {
	TO_BE_ACTIVATED_AFTER_THIRD_PARTY_CREATION = "TO_BE_ACTIVATED_AFTER_THIRD_PARTY_CREATION",
	TO_BE_ACTIVATED_AFTER_ENROLMENT = "TO_BE_ACTIVATED_AFTER_ENROLMENT",
	ACTIVATED = "ACTIVATED",
}
